@startuml
'https://plantuml.com/activity-diagram-beta
Title Aktivitets Diagram (TO-BE)
|k| Kunde
start
:Gå til website;
|w|
:Vis hjemmeside;
|k|
:Valg skræddersyet carport i navbar;

|#003D76|w| Website

|k|
:opret eller login;
repeat
|k|
:Indtast mål;
|w|
  :valider input;
repeat while (mangler data) is (data mangler)
->data er ok;

|w|
:opret forespørgsel/bestilling i DB;

fork
|w|
:;
|k|
:Se tegning;
end
fork again
  |s|
  :Sælger ser at der er kommet en bestilling;
end merge
|w|
:se tegning og stykliste;

|s|Fog
:Sælger snakker med kunde, giver vejledning, justerer ordre;
:giver pris til kunde;
|k|
:modtager pris;
|s|
:Bekræfter/redigere ordre,
laver bindende aftale med kunden;

|w|
:opdatere ordre i DB;
|k|
:Betaler;
|w|
:opdatere ordre i DB;
|k|
:Får stykliste;
|s|
:Leverer materialer;
|k|
:Bygger carport;
stop
@enduml